### PR TITLE
New VizFrame Chart control demo

### PR DESCRIPTION
**Pull request by axelmohnen**
Demo class: Z2UI5_CL_DEMO_APP_312
List of methods:
VIZ_FRAME
VIZ_DATASET
VIZ_FLATTENED_DATASET
VIZ_DIMENSIONS
VIZ_DIMENSION_DEFINITION
VIZ_MEASURES
VIZ_MEASURE_DEFINITION
VIZ_FEEDS
VIZ_FEED_ITEM

### CODE REVIEW

**Comment by axelmohnen** [comment]
New VizFrame Chart control
Demo class: Z2UI5_CL_DEMO_APP_312
List of methods:
VIZ_FRAME
VIZ_DATASET
VIZ_FLATTENED_DATASET
VIZ_DIMENSIONS
VIZ_DIMENSION_DEFINITION
VIZ_MEASURES
VIZ_MEASURE_DEFINITION
VIZ_FEEDS
VIZ_FEED_ITEM

**Comment by oblomov-dev** [comment]
@axelmohnen thanks for the PRs.

when i start the sample i get:
image

In my console i get the following error:
image

I hope i did not mess something up with the PRs. Which UI5 version do you use?

**Comment by axelmohnen** [comment]
Hi @oblomov-dev,
We are using local SAPUI5 version 1.108.19.

Maybe the issue comes from the different namspaces?
Do we have to maintain the NS with "xmlns:" or without?

image

**Comment by oblomov-dev** [comment]
mhh then my version should be high enough.

xmlns is added automatically at a later point, so no need for that. i already deleted it.

**Comment by oblomov-dev** [comment]
ah overlooked this, thanks for the hint, fixed with:
https://github.com/abap2UI5/abap2UI5/pull/1607

Now it works:
image

This is awesome — thanks a lot for the sample!

Currently, I create a lot of posts on LinkedIn when people contribute to showcase that this is a community-driven project. I'd be happy to create a post about this sample as well! If you’re okay with it, feel free to share your LinkedIn name so I can credit you as a contributor. Of course, no pressure if you’d prefer not to — totally fine either way. 😊

**Comment by axelmohnen** [comment]
Great News! 
Sure no problem.
Here is my LinkedIn profile: 
[linkedin.com/in/axel-mohnen-ab182a164](https://www.linkedin.com/in/axel-mohnen-ab182a164)

Thanks a lot
Axel

**Pull request merged**
